### ISSUE TITLE
Add a section on procurement procedures

### ISSUE THREAD

**Issue by shoaibsufi** [softwaresaved/event-organisation-guide#2]

**Comment by npch** [comment]
@shoaibsufi where should I put this in the EOG? It's related to a number of things (e.g. venue, catering, other services) but not sure if it should have its own section, or should just be mentioned as part of the first thing that you're likely to encounter (probably venue).

Also, there isn't currently a section on choosing a venue in the EOG - should I raise an issue for that?

**Comment by shoaibsufi** [comment]
Venue is mentioned here - https://event-organisation-guide.readthedocs.io/en/latest/eog/feasibility-stage.html

If the information is better to add in different places I am ok with that
