### ISSUE TITLE
Add accommodation requirements

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/event-organisation-guide#22]
From Neil: It seems like there will be some locations where hotel cancellation policies are less flexible – could we add something to our Event Organisation Guide that reminds organisers to look into accommodation as soon as possible a location is fixed (and ideally before registration is opened), and that cancellation policy is one of the things that should be included in the requirements for hotel suppliers?

**Comment by shoaibsufi** [comment]
Added a new file eps-accommodation.rst / section in the Event Project Stage to highlight more active management of accommodation for events.
