### ISSUE TITLE
Add brief paragraph on audiovisuals to publicity section

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#24]
At Shoaib's request, I've gone through the guide and I've noticed that we don't mention anything about photographing the event or recording the sessions. We should add that to the before the event and during subsections.

**Comment by shoaibsufi** [comment]
We need a mention what we do with video - i.e. we record and upload

- like the videos at CW19
E.g. https://www.youtube.com/watch?v=_olNuVusJzU

**Comment by shoaibsufi** [comment]
I have added text on Photography - the session recordings are more of an output than publicity - yes they can be used for publicity - but we did do videos for publicity only reasons
