### ISSUE TITLE
External links to open in new tab

### ISSUE THREAD

**Issue by anenadic** [softwaresaved/event-organisation-guide#26]
All links to external google docs open in the same tab - so the reader loses the guide.
Here is how to do it in reStructuredText, there does not seem to be an easy solution: https://stackoverflow.com/questions/11716781/open-a-link-in-a-new-window-in-restructuredtext

**Comment by shoaibsufi** [comment]
Hi Aleks, I would rather have clarity in the code and the format - I want to avoid magic - I can wait for reStructuredText to catch up or just live with it for now - or for something in the official theme to change. So I am labelling this wontfix for now. If we get lots of feedback then we can revisit.
