### ISSUE TITLE
Making the SSI acknowledgement more visible

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#29]
@shoaibsufi @anenadic We note in the introduction that this is an SSI guide, but we're assuming that people will read the introduction. Can we acknowledge that this is an SSI guide somewhere in the index or the footer? 

A question related to this: is it possible to add the SSI logo onto Read the Docs?

**Comment by shoaibsufi** [comment]
Add this to the copyright line in the footer  ... on behalf of the Software Sustainability Institute.
