### ISSUE TITLE
'When to start planning' clarification

### ISSUE THREAD

**Issue by JacalynLaird** [softwaresaved/event-organisation-guide#30]
"For events such as a Collaborations Workshop, it’s important that the idea and feasibility stages start early" - what is it about CW that requires this? Clarify e.g. "for large events..." or "for complex events" etc.

**Comment by shoaibsufi** [comment]
More a case of complexity first rather than size - but do clarify

**Comment by shoaibsufi** [comment]
changes made to when-to-start.rst
