### ISSUE TITLE
use of acronyms

### ISSUE THREAD

**Issue by JacalynLaird** [softwaresaved/event-organisation-guide#31]
I would recommend dropping the use of acronyms for the stages (IES, FS, EPS) as they don't seem necessary. 

If you think they should be kept then they need to be used consistently. Either way need to check the document for their use as there are issues like this:
"An overall goal and aim should crystallise by the end of the **IES stage**, but this is more formally detailed as part of the **FS stage**."

**Comment by shoaibsufi** [comment]
Decide to use the stage name in full rather than the acronym  - and maybe. make them shorter.
