### ISSUE TITLE
Comms edits of templates

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#34]
I created a copy of all templates to be able to edit them without making the edits public to anyone who accesses the guide. The edits are: https://drive.google.com/drive/u/3/folders/1zEaR1kcPVNk1QvYoMJ7SivKhSl5G6U8A

The "event roles" template needs to be heavily edited before we publish the guide: https://docs.google.com/document/d/1mSDWtaD6Q96hwkmLq1VRMZZWhkn_6WJzIZ48Uv8ZRug/edit

The "duties roster" template also needs to be reviewed and heavily edited before publishing the guide: 
https://docs.google.com/document/d/1s-v47pj2pe4QHCuo763lwJYvSofJ1AV2pOxvrm3XKhc/edit#heading=h.vmy9cnjzkk1y

**Comment by shoaibsufi** [comment]
I have updated the event roles one - https://docs.google.com/document/d/1mSDWtaD6Q96hwkmLq1VRMZZWhkn_6WJzIZ48Uv8ZRug/edit#

(Note I think I might need to top and tail this with extra info and put on Zenodo as that's the plan going forward - i.e. for templates to be on Zenodo rather than the google drive) - but first stage is going through all the suggests

**Comment by shoaibsufi** [comment]
Check the directory as all templates were commented on - the above ones were specifically mentioned as they had a lot of changes

**Comment by shoaibsufi** [comment]
Event Roles - https://zenodo.org/record/3967427 and Event Duties Roster - https://zenodo.org/record/3967445 now up on Zenodo

**Comment by shoaibsufi** [comment]
Venue requirements is also updated as is eps-venue.rst - https://zenodo.org/record/4064079

**Comment by shoaibsufi** [comment]
Event Timeline is now also updated as is eps-timeline.rst - https://zenodo.org/record/4066931

**Comment by shoaibsufi** [comment]
Budget template is updated where it is referenced and is on Zenodo - https://zenodo.org/record/4071896

**Comment by shoaibsufi** [comment]
Risk Management template is now updated and referenced in EOG and uploaded to Zenodo - https://zenodo.org/record/4088024

**Comment by shoaibsufi** [comment]
All the comments have been addressed and the updates have been made so closing the issue
