### ISSUE TITLE
Write contributing guidelines

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/event-organisation-guide#40]
Write up some contributing guidelines in a CONTRIBUTING.md

Include instructions on what we are looking for (content based on experience not theory, case studies), the different pathways to contributing (e.g. via GitHub, Google Forms), and governance (authorship vs contributors).

**Comment by rainsworth** [comment]
Should also add a code of conduct (and work through the [Community Profile checklist](https://github.com/softwaresaved/event-organisation-guide/community)).

**Comment by rainsworth** [comment]
Include guidance of the following from @shoaibsufi in PR #43:
> A lot of the bulleted lists contain sentence fragments that do not require capitalisation or full stops - see - https://www.grammarly.com/blog/bullet-points/
> 
> _Punctuation with bullet points
> 
> If the text of your bullet point is a complete sentence (or multiple sentences), use capital letters and punctuation. If your points are not structured as proper sentences, you don’t need to end with punctuation. Capitalization is a style choice—with sentence fragments, you can choose to start each with either upper- or lower-case letters._
> 
> Can you remove the full stops from the sentence fragments - we can keep the capital at the beginning.

**Comment by shoaibsufi** [comment]
added to STYLE.md and have written up some initial CONTRIBUTING.md

**Comment by shoaibsufi** [comment]
added section on document change process

**Comment by shoaibsufi** [comment]
Clarified Authorship vs Contributor vs thanks.
