### ISSUE TITLE
Enable autobuild of pull requests

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/event-organisation-guide#45]
Enable the Read the Docs autobuild feature to preview the changes made in a pull request on the web instead of having to build locally: https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html

To do this
1. The maintainer needs to go to https://readthedocs.org/projects/event-organisation-guide/
2. Click the Admin button
3. Go to Advanced Settings
4. Check the box next to "Build pull requests for this project "

**Comment by rainsworth** [comment]
(I am also happy to be added as a maintainer on Read the Docs if that is helpful.)

**Comment by shoaibsufi** [comment]
ok - this is done

And I have added you as a maintainer by adding the rainsworth user
