### ISSUE TITLE
EOG 'Publicity' page - contact details

### ISSUE THREAD

**Issue by JacalynLaird** [softwaresaved/event-organisation-guide#52]
I'd remove contact details from this list. 
From a GDPR point of view the contact details should be kept secure, e.g. in a locked folder, whereas the publicity plan could be accessible to lots of people.

**Comment by shoaibsufi** [comment]
For the plan to be useful it needs to have the contact details in it. For example - for CW the contact details are accessible to the whole SSI team - but from a GDPR perspective that works - as we all have the same rights through our institutions. The publicity plan is meant to accessed by only the people on the project / event to deliver it - so I don't see the need for the separation.

**Comment by shoaibsufi** [comment]
@JacalynLaird - if you have further info or I have missed something feel free to add it as a comment there - I might ping Neil if we can’t get our heads around this one - as he is very GDPR knowledgeable

**Comment by shoaibsufi** [comment]
ok - I have added what you suggested.
