### ISSUE TITLE
Risk assessment & risk proximity

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#54]
In the [risk assessment](https://github.com/softwaresaved/event-organisation-guide/blob/comms-edits2/docs/eog/eps-risk-management.rst) chapter, we mention risk proximity as another value to be considered in the risk management matrix. We don't include it in the guide, but there is no explanation for this decision. Can we include a sentence as to why we're not including it?

**Comment by shoaibsufi** [comment]
further comment from the commit messages - from @selina-aragon : There is no explanation as to why we don't include risk proximity in the approach included in the guide. I'm assuming we also don't use it for any of our events. Can we explain why?

**Comment by shoaibsufi** [comment]
We have not used risk proximity formally in planning of events, it's included in the EOG as a note to help people who want to go the extra mile. EOG is focused mainly experiential knowledge -  'https://github.com/softwaresaved/event-organisation-guide/blob/master/CONTRIBUTING.md

We might use it in the future - it would also add a lot of complexity to the example making the the risk assessment matrix 3 dimensional. I will just add a note to say we did not use it and therefore don't describe its use.

**Comment by selina-aragon** [comment]
I'm ok with that. However, I think the note should also mention your reasons for not using it (i.e. EOG is focused on mainly experiential knowledge and so far none of our events have used it formally, or something like that).
