### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by JacalynLaird** [softwaresaved/event-organisation-guide#55]
It might be worth putting together a checklist/one per event stage - a useful quick reference for people. Could be down the line i.e. after the initial version is published

**Comment by shoaibsufi** [comment]
@JacalynLaird I am going to change the label on this one to 'enhancement' and we can punt it to a future version - what do you think? (as I am taking closing all the comms-edits labelled ones as things we need to close to get the version out)

**Comment by JacalynLaird** [comment]
Agreed

**Comment by shoaibsufi** [comment]
For the record - this is a task now for a future version of EOG (after the one done in Dec 2020).

**Comment by shoaibsufi** [comment]
this is the same as #78 so I am closing it.
