### ISSUE TITLE
CW20 case study

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#56]
Overall, the CW20 case study is a great way of seeing the EOG in practice, and it's an excellent record of what happened in terms of planning and organisation of the event. 

However, it's very long. I don't think it's necessary to write another one though, as we can probably use a re-jigged version of the CW20 blogpost: https://software.ac.uk/blog/2020-05-18-cw20-how-move-event-online-three-weeks. 

So, my suggestion would be that we keep the CW20 as is in the guide as a thorough example of each of the EOG stages, but add a re-jigged version of the blog post as the case study (which would be added instead of the current introduction). 

Happy to chat about this further if anyone has any ideas or suggestions.

**Comment by shoaibsufi** [comment]
We (@rainsworth and I) were thinking a statement on the intro page directing to the blog post for the summary version and explaining that what is below is a detailed exposition of how activities match to the different stages of the EOG would be sufficient rather than a re-jig/summary of the blog post - what do you think @selina-aragon?

**Comment by selina-aragon** [comment]
I agree with not creating another version of the blog post, but I think we need to rephrase/rename our titles as the longer version isn't a case study, whereas the blog post version reads a lot more like one. Maybe let's have a chat about this one?

**Comment by shoaibsufi** [comment]
ok - I will email about setting up a meeting.

**Comment by shoaibsufi** [comment]
From comms/community meeting 2020-12-03:

SSI use case study to mean something quite concise that highlights benefits and things learnt - so we will make EOG consistent with that use of the terminology and change Case Study to EOG in Practice in the EOG.

**Comment by shoaibsufi** [comment]
![Screenshot 2020-12-03 at 10 48 17](https://user-images.githubusercontent.com/473827/100999803-0eb27200-3555-11eb-8a53-340a0597f06f.png)

**Comment by shoaibsufi** [comment]
Terminology and directory structure updated to reflect 'In Practice' write-ups vs 'Case Studies'.
