### ISSUE TITLE
re-word first sentence in the outcomes section in eps-outputs-and-outcomes.rst

### ISSUE THREAD

**Issue by shoaibsufi** [softwaresaved/event-organisation-guide#60]
**Describe the change being requested**
From @JacalynLaird : I think the first sentence of the outcomes section needs reworded. I haven't done this as don't want to accidentally change the meaning - happy to discuss.

**State the reason for the change**
Clarifying

**Describe the impact of the change on other parts of the SSI-EOG**
N/A

**Describe any alternatives you have considered (if applicable)**
N/A

**Additional context**

**Comment by shoaibsufi** [comment]
The section has been updated as follows:

.. _Outputs-And-Outcomes:
  
Outputs and Outcomes Plan
=========================
Outputs
*******
It's important to plan what you will make available after the event.  For instance, for a Collaborations Workshop type of event these normally include:

- Presentations
    - From keynotes (slides, videos)
    - From lightning talks  (slides, videos)
    - From mini-workshops (slides)

- Speed blog posts
    - From discussion sessions

- Collaborative ideas
    - Making the final ideas available

- Hackday
    - Information about entries and winners
    - Team/Project name
    - Presentations
    - Links to the software/output

Outcomes 
******** 
Outcomes tend to match objectives but the Event Lead should decide if a report or thematic analysis of the workshop outputs might help highlight any change of outlook due to the workshop.
Feedback results can also be part of this. Longer term analysis (e.g. surveys after the event may also be useful to see if the workshop has, for instance, changed practice or led to further collaborations). See the `Ten simple rules for measuring the impact of workshops <https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006191>`_ for more ideas and guidance.

**Comment by shoaibsufi** [comment]
@JacalynLaird - what do you think about the above - I will add it to the list of things to discuss in the meeting as you did originally suggest a discussion.

**Comment by JacalynLaird** [comment]
This is clearer now.

**Comment by shoaibsufi** [comment]
Thanks - I will close this now.
