### ISSUE TITLE
Venue requirements template edits

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#66]
The Comms team has made edits to the Venue Requirement template. Please use this issue to track any comments or queries of the changes. 

The edited template can be found in Google Drive: https://docs.google.com/document/d/1pi-LR1ZOepiDzeGMYKONEXaSUROhKrnD/edit?rtpof=true

**Comment by shoaibsufi** [comment]
Copy made and changes to - https://docs.google.com/document/d/1NNu95Q4Vxtsyhnl7RALbwDBMJGoZxUqB/edit#heading=h.gjdgxs
