### ISSUE TITLE
Risk Management template edits

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#67]
The Comms team has made edits to the Risk Management template. Please use this issue to track any comments or queries of the changes.

Please note that I (Selina) have made comments throughout the document, but I've also added minor edits (punctuation or typo corrections) **without tracking** (it's quite hard to track on a spreadsheet). Please copy or re-upload this document, rather than make the edits in the comments to a different document. 

The edited template can be found in Google Drive: https://docs.google.com/spreadsheets/d/1qYBB6jRJDZefpA_iK_rX6w9sQVuLEuDI/edit#gid=1607530999

**Comment by shoaibsufi** [comment]
Copy and changes at - https://docs.google.com/spreadsheets/d/1HU_1UP3aLNozHnJf8GSxY0N9RDbq7fDk/edit#gid=1607530999
