### ISSUE TITLE
Event Timeline template edits

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#68]
The Comms team has made edits to the Event Timeline template. Please use this issue to track any comments or queries of the changes.

The edited template can be found in Google Drive: 

https://docs.google.com/document/d/1MGDZ4_4Q5-oazKR--Wjd45anna0os6o5/edit?rtpof=true

**Comment by shoaibsufi** [comment]
I have made a copy and I am updating it here - https://docs.google.com/document/d/1ZV-Uds5NhtjODLwuiH-l-kvOO-pqbmvV/edit#heading=h.gjdgxs
