### ISSUE TITLE
Event Duties Roster template edits

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#70]
The Comms team has made edits to the Event Duties Roster template. Please use this issue to track any comments or queries of the changes.

The edited template can be found in Google Drive: 
https://docs.google.com/document/d/1SgqeuElzmpqkAirNWMaDCpgJ7SciGVD5/edit#heading=h.gjdgxs

**Comment by shoaibsufi** [comment]
So I am updating a copy here (with comments preserved) - https://docs.google.com/document/d/1V4jwde62_Rb6CD3laQM9h475v60aVG_q/edit#
