### ISSUE TITLE
Budget template edits

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#71]
The Comms team has made edits to the Budget template. Please use this issue to track any comments or queries of the changes.

I've made minor edits (punctuation or typo corrections) without tracking (it's quite hard to track on a spreadsheet). Please copy or upload this document, rather than make the edits in the comments to a different document.

The edited template can be found in Google Drive: 
https://docs.google.com/spreadsheets/d/15U3DxXlAoa8VzYOqgheuu07U6wTvpQB-/edit#gid=41781067

**Comment by shoaibsufi** [comment]
So I took a copy and this is the one I will upload - just waiting for comments in the slack

https://docs.google.com/spreadsheets/d/1YbTtbfxDSRnSUKAHOC2GLpgN5xjH5Dau/edit#gid=41781067
